### PR TITLE
Update the latest Tmail image for Integration tests

### PR DESCRIPTION
**Pull request by quantranhong1999**
```
[error] Failed tests:
[error] 	org.apache.james.gatling.jmap.rfc8621.WebsocketSimpleIT
[error] 	org.apache.james.gatling.jmap.rfc8621.PushPlatformValidationIT
[error] (Gatling-it / test) sbt.TestsFailedException: Tests unsuccessful
```

Details: Only failing on Close websocket request
image

Me I do not think this is James' side. Finding something could be related to Gatling's side...

`REQUEST	1		Close websocket	1647249935294	1647249935311	KO	Premature close`

### CODE REVIEW

**Review by Arsnael — APPROVED** [review]

**Comment by Arsnael** [comment]
Needs more investigating

**Comment by quantranhong1999** [comment]
https://github.com/gatling/gatling/issues/3958

Could be related. So I plan to refactor/upgrade Gatling to an upward 3.4.0 version.
=> I just try a bit of upgrade, it is gonna the pain...

CF: https://groups.google.com/g/gatling/c/D0g7I6Htpno
`You get a "Premature close": either when we've received a partial response, then the connection was closed, or...`
=> Could be on James' side also.

Not sure where to take effort. What do you think?

**Comment by chibenwa** [comment]
M yes we can take time to upgrade gatling version (here and on gatling-imap)

**Comment by quantranhong1999** [comment]
Can we do something like [this](https://github.com/quantranhong1999/james-gatling/pull/2/commits/3f08aa1625418464913a20c7dbebb7b24f152503) to fix the failing tests?

While we have not upgraded Gatling yet, we could comment that lines. Eventually, when the test finishes, the container shuts down and the socket connection also closes.

**Comment by chibenwa** [comment]
>Can we do something like [this](https://github.com/quantranhong1999/james-gatling/pull/2/commits/3f08aa1625418464913a20c7dbebb7b24f152503) to fix the failing tests?
>
>While we have not upgraded Gatling yet, we could comment that lines. Eventually, when the test finishes, the container shuts down and the socket connection also closes.

Ok to me as long as it's written somewhere that we need to re-enable it once we upgraded Gatling

**Comment by quantranhong1999** [comment]
Here we go: https://app.zenhub.com/workspaces/team-james-5873652b2a0b13cc0b8bbe63/issues/linagora/james-project-private/368

Let's finish [Run James Gatling build with Jenkins](https://app.zenhub.com/workspaces/team-james-5873652b2a0b13cc0b8bbe63/issues/linagora/james-project-private/363) here.

**Review by chibenwa — APPROVED** [review]

**Review by Arsnael — APPROVED** [review]

**Pull request merged**
