### PR TITLE
Fix Jmap tests

### PR DESCRIPTION
**Pull request by blackheaven**

### CODE REVIEW

**Review by remk — APPROVED** [review]

**Review by rouazana — APPROVED** [review]

**Review by Arsnael — APPROVED** [review]

**Review by mbaechler — APPROVED** [review]
It looks like it still doesn't compile.

**Comment by blackheaven** [comment]
it should have fixed it...

**Comment by rouazana** [comment]
In fact it's just ImapAuthenticationIT that is not finishing, making the build timeout

**Comment by rouazana** [comment]
seems related to:
```
17:53:32.663 [GatlingSystem-akka.actor.default-dispatcher-7] ERROR akka.actor.OneForOneStrategy - Actor com.linagora.gatling.imap.protocol.ImapSession@51eb248a doesn't support message Connect(UserId(1))
java.lang.IllegalArgumentException: Actor com.linagora.gatling.imap.protocol.ImapSession@51eb248a doesn't support message Connect(UserId(1))
```

**Comment by blackheaven** [comment]
It was broken before, IIRC @remk fixed it but I did not find the commit.

I just intended to have a source code compiling and a CI.

**Comment by rouazana** [comment]
see https://github.com/linagora/james-gatling/pull/65

**Pull request closed without merging**
