### PR TITLE
Fetch full message and not only bodystructure

### PR DESCRIPTION
**Pull request by remk**

### CODE REVIEW

**Review by Arsnael — APPROVED** [review]
Nice catch, thanks @remk

**Review by rouazana — APPROVED** [review]

**Comment by chibenwa** [comment]
It do not change much on the DB reads, however transmitting more info on the wire to gatling might worsen memory problems.

How do we stand after this fix regarding memory usage? Still able to run 4000 users on the plateform simulation stuff?

**Comment by remk** [comment]
> It do not change much on the DB reads, however transmitting more info on the wire to gatling might worsen memory problems.
> 
> How do we stand after this fix regarding memory usage? Still able to run 4000 users on the plateform simulation stuff?

Yes, i ran the platform simulation with 5k users, it broke around 4600 by an out of memory exception in gatling.

**Comment by chibenwa** [comment]
Ok :+1: then as it to not bring more limitations

**Pull request merged**
