### PR TITLE
ISSUE-147 Port PushPlatformValidationScenario to pure RFC-8621

### LINKED ISSUE #147: Port PushPlatformValidationScenario to pure RFC-8621
Get rid of the following imports:

```
import org.apache.james.gatling.jmap.draft.JmapMessages.openpaasListMessageParameters
import org.apache.james.gatling.jmap.draft.scenari.{JmapInboxHomeLoadingScenario, JmapOpenArbitraryMessageScenario, JmapSelectArbitraryMailboxScenario}
import org.apache.james.gatling.jmap.draft.{CommonSteps, JmapMessages}
```

Have a run to find system limits.

### PR DESCRIPTION
**Pull request by vttranlina**
resolve https://github.com/linagora/james-gatling/issues/147

### CODE REVIEW

**Review by Arsnael — APPROVED** [review]

**Review by chibenwa — APPROVED** [review]

**Comment by chibenwa** [comment]
Can we get a run for this on preprod ?

**Review by quantranhong1999 — APPROVED** [review]

**Comment by vttranlina** [comment]
# Gatling result
preprod-1 pod

1. 1k user - 15m

screencapture-file-home-tungtv-workplace-tmp-gatling-1000-15m-index-html-2022-05-25-17_55_48

2. 5k user - 15m

screencapture-file-home-tungtv-workplace-tmp-gatling-5000-15m-index-html-2022-05-25-17_57_26


4. 10k user - 15m

screencapture-file-home-tungtv-workplace-tmp-gatling-10000-15m-index-html-2022-05-25-17_58_35

**Comment by chibenwa** [comment]
How many JMAP PODs?

**Comment by vttranlina** [comment]
> How many JMAP PODs?

1pod

**Pull request merged**
